// <auto-generated />
namespace FootballDatabase.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CountryTeamandTownValidations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountryTeamandTownValidations));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081514322_Country, Team and Town Validations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
