// <auto-generated />
namespace FootballDatabase.Data.SqlServerMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OwnerAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OwnerAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201706120955022_OwnerAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
